### ISSUE TITLE
JSAPI not rendering all returned features

### ISSUE THREAD

**Issue by MarkTorrey** [koopjs/koop-provider-composite#6]
Viewing service in the map viewer does not render all features returned. I think this may be something to do with tiled query requests...not sure if this is related to #4? Making requests directly to the service through postman returns proper number of features.
![features_not_rendered](https://user-images.githubusercontent.com/1084420/31669040-e996457c-b321-11e7-9b73-6e67c052a87d.png)

these manually queries combined return all features in the above extent
http://localhost:3001/composite/addresses/featureserver/0/query?f=json&returnGeometry=true&spatialRel=esriSpatialRelIntersects&geometry=%7B%22xmin%22%3A-8783378.923690563%2C%22ymin%22%3A4325418.561405674%2C%22xmax%22%3A-8783226.04963404%2C%22ymax%22%3A4325571.435462197%2C%22spatialReference%22%3A%7B%22wkid%22%3A102100%2C%22latestWkid%22%3A3857%7D%7D&geometryType=esriGeometryEnvelope&inSR=102100&outFields=*&outSR=102100

http://localhost:3001/composite/addresses/featureserver/0/query?f=json&returnGeometry=true&spatialRel=esriSpatialRelIntersects&geometry=%7B%22xmin%22%3A-8783073.175577516%2C%22ymin%22%3A4325418.561405674%2C%22xmax%22%3A-8782920.301520992%2C%22ymax%22%3A4325571.435462197%2C%22spatialReference%22%3A%7B%22wkid%22%3A102100%2C%22latestWkid%22%3A3857%7D%7D&geometryType=esriGeometryEnvelope&inSR=102100&outFields=*&outSR=102100

http://localhost:3001/composite/addresses/featureserver/0/query?f=json&returnGeometry=true&spatialRel=esriSpatialRelIntersects&geometry=%7B%22xmin%22%3A-8783226.04963404%2C%22ymin%22%3A4325265.68734915%2C%22xmax%22%3A-8783073.175577516%2C%22ymax%22%3A4325418.561405674%2C%22spatialReference%22%3A%7B%22wkid%22%3A102100%2C%22latestWkid%22%3A3857%7D%7D&geometryType=esriGeometryEnvelope&inSR=102100&outFields=*&outSR=102100

etc...

**Comment by MarkTorrey** [comment]
@ajturner, @dmfenton , @adamajm

Adding an AggregateID (aid) field to the baseSchema and setting that to a machine generated number (not sure how random this will be, and there might be a case where there could be collisions) looks to have fixed the random rendering behavior we were seeing earlier...

https://github.com/koopjs/koop-provider-composite/blob/3d8e4d72c83369b6b37269d0b56cc30942b2cdc0/model.js#L332

![oid_issue](https://user-images.githubusercontent.com/1084420/31737311-0af7c1e8-b415-11e7-86d0-d4581f80cba0.PNG)

**Comment by dmfenton** [comment]
Booyah!

**Comment by dmfenton** [comment]
Now I need some way to make this happen automagically inside Koop because other providers will have this issue too.

**Comment by dmfenton** [comment]
@MarkTorrey did you see my suggestion for a better way to calculate this objectid?
